### ISSUE TITLE
Dealing with last line being different

### ISSUE THREAD

**Issue by bpbp-boop** [giftcards/FixedWidth#12]
I'm trying to parse a fixed width file:
```
        $spec = $this->buildSpec();

        $file = new \SplFileInfo('THEFILE');
        $factory = new FileFactory($spec);
        $reader = $factory->createReader($factory->createFromFile($file), 'spec1');
```

Unfortunately my file is all the same width except for the very last line, which is one character long and seems to be a sort of terminating character (editor displays 'SUB') so I get

> InvalidArgumentException: All lines in a batch file must be 514 chars wide this line is 1 chars wide. in ./vendor/giftcards/fixed-width/src/Giftcards/FixedWidth/AbstractFile.php on line 60

Is there something I put in my spec to recognize this character as the end of the file? Or should I trim the file before loading it?

**Comment by yjv** [comment]
@bpbp-boop interesting. Do you think this character may be on all of your new lines? If not is there some sort of way the file is being curropted? I guess in direct answer to your question, the spec only helps in parsing the already split lines really. The basic requirement of fixed width files having all the same line lengths is sort of inheerant to fixed width files. perhaps an option could be added to allow for the last line to have extra chars but in general iw ould say the good default would be what its doing.

What do you think?

thanks!

**Comment by bpbp-boop** [comment]
I've checked a bunch of these files, they all seem to be terminated with 'SUB' aka Ctrl-Z. I think it's an old MS-DOS convention. I'll deal with these EOF markers manually before sending to FixedWidth I think. Thanks!

**Comment by yjv** [comment]
No problem thank you
